CREATE TYPE "user_role" AS ENUM (
  'student',
  'admin',
  'personnel'
);

CREATE TYPE "user_status" AS ENUM (
  'active',
  'inactive',
  'suspended'
);

CREATE TYPE "allowlist_status" AS ENUM (
  'pending',
  'registered'
);

CREATE TYPE "program_status" AS ENUM (
  'open',
  'under_review',
  'closed'
);

CREATE TYPE "application_status" AS ENUM (
  'pending',
  'under_review',
  'approved',
  'rejected'
);

CREATE TYPE "parent_type" AS ENUM (
  'father',
  'mother',
  'guardian'
);

CREATE TYPE "document_type" AS ENUM (
  'four_ps',
  'pwd',
  'ip'
);

CREATE TYPE "payout_semester" AS ENUM (
  'first_sem',
  'second_sem'
);

CREATE TYPE "payout_status" AS ENUM (
  'pending',
  'released'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "role" user_role NOT NULL,
  "status" user_status DEFAULT 'active',
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp
);

CREATE TABLE "student_allowlist" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_number" varchar(100) UNIQUE NOT NULL,
  "registration_status" allowlist_status DEFAULT 'pending',
  "uploaded_by" int NOT NULL,
  "uploaded_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "registered_at" timestamp
);

CREATE TABLE "students" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "student_number" varchar(100) UNIQUE NOT NULL,
  "first_name" varchar(100) NOT NULL,
  "middle_name" varchar(100),
  "last_name" varchar(100) NOT NULL,
  "birthdate" date,
  "gender" varchar(50),
  "contact_number" varchar(50),
  "address" text,
  "school_name" varchar(255),
  "course" varchar(255),
  "year_level" int,
  "gwa" decimal(4,2),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp
);

CREATE TABLE "staff_profiles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "first_name" varchar(100) NOT NULL,
  "last_name" varchar(100) NOT NULL,
  "department" varchar(150),
  "position" varchar(150),
  "contact_number" varchar(50),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp
);

CREATE TABLE "scholarship_programs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "description" text,
  "school_year" varchar(20) NOT NULL,
  "total_budget" decimal(12,2) NOT NULL,
  "amount_per_student" decimal(12,2),
  "status" program_status DEFAULT 'open',
  "created_by" int NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp
);

CREATE TABLE "applications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" int NOT NULL,
  "program_id" int NOT NULL,
  "school_year" varchar(20) NOT NULL,
  "status" application_status DEFAULT 'pending',
  "rank" int,
  "reviewed_by" int,
  "reviewed_at" timestamp,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp
);

CREATE TABLE "application_personal_info" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "application_id" int UNIQUE NOT NULL,
  "first_name" varchar(100) NOT NULL,
  "middle_name" varchar(100),
  "last_name" varchar(100) NOT NULL,
  "birthdate" date,
  "gender" varchar(50),
  "contact_number" varchar(50),
  "address" text,
  "school_name" varchar(255),
  "course" varchar(255),
  "year_level" int,
  "gwa" decimal(4,2),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "application_parents" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "application_id" int NOT NULL,
  "type" parent_type NOT NULL,
  "first_name" varchar(100),
  "middle_name" varchar(100),
  "last_name" varchar(100),
  "occupation" varchar(150),
  "monthly_income" decimal(10,2),
  "contact_number" varchar(50),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "application_documents" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "application_id" int NOT NULL,
  "document_type" document_type NOT NULL,
  "file_path" varchar(500) NOT NULL,
  "file_name" varchar(255),
  "mime_type" varchar(100),
  "uploaded_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "payouts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "application_id" int NOT NULL,
  "semester" payout_semester NOT NULL,
  "amount" decimal(10,2) NOT NULL,
  "status" payout_status DEFAULT 'pending',
  "released_by" int,
  "released_at" timestamp,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

ALTER TABLE "students" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "staff_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "student_allowlist" ADD FOREIGN KEY ("uploaded_by") REFERENCES "staff_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "students" ADD FOREIGN KEY ("student_number") REFERENCES "student_allowlist" ("student_number") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "scholarship_programs" ADD FOREIGN KEY ("created_by") REFERENCES "staff_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applications" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applications" ADD FOREIGN KEY ("program_id") REFERENCES "scholarship_programs" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applications" ADD FOREIGN KEY ("reviewed_by") REFERENCES "staff_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "application_personal_info" ADD FOREIGN KEY ("application_id") REFERENCES "applications" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "application_parents" ADD FOREIGN KEY ("application_id") REFERENCES "applications" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "application_documents" ADD FOREIGN KEY ("application_id") REFERENCES "applications" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payouts" ADD FOREIGN KEY ("application_id") REFERENCES "applications" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payouts" ADD FOREIGN KEY ("released_by") REFERENCES "staff_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;
